/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 27-bře-2017 19:34:59 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `Users` CASCADE
;

DROP TABLE IF EXISTS `Tasks` CASCADE
;

DROP TABLE IF EXISTS `Projects` CASCADE
;

/* Create Tables */

CREATE TABLE `Users`
(
	`ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`FirstName` VARCHAR(32) 	 NULL,
	`LastName` VARCHAR(32) 	 NULL,
	`Username` VARCHAR(16) NOT NULL,
	`Password` VARCHAR(32) NOT NULL,
	`IsEmployee` BOOL NOT NULL,
	`EMail` VARCHAR(32) 	 NULL,
	`TelNumber` VARCHAR(16) 	 NULL,
	`Avatar` BLOB 	 NULL,
	CONSTRAINT `PK_Users` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Tasks`
(
	`ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(32) 	 NULL,
	`Description` TEXT 	 NULL,
	`Code` VARCHAR(8) 	 NULL,
	`StartDate` DATE 	 NULL,
	`PlanEndDate` DATE 	 NULL,
	`EndDate` DATE 	 NULL,
	`Project_ID` INTEGER UNSIGNED NOT NULL,
	`User_ID` INTEGER 	 UNSIGNED NULL,
	CONSTRAINT `PK_Tasks` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Projects`
(
	`ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(32) NOT NULL,
	`Description` TEXT 	 NULL,
	`Code` VARCHAR(8) NOT NULL,
	`StartDate` DATE NOT NULL,
	`PlanEndDate` DATE 	 NULL,
	`EndDate` DATE 	 NULL,
	`User_ID` INTEGER UNSIGNED NOT NULL,
	CONSTRAINT `PK_Projects` PRIMARY KEY (`ID`)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Tasks` 
 ADD CONSTRAINT `FK_Tasks_Projects`
	FOREIGN KEY (`Project_ID`) REFERENCES `Projects` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Tasks` 
 ADD CONSTRAINT `FK_Tasks_Users`
	FOREIGN KEY (`User_ID`) REFERENCES `Users` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Projects` 
 ADD CONSTRAINT `FK_Projects_Users`
	FOREIGN KEY (`User_ID`) REFERENCES `Users` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 ;
