/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 01-dub-2017 16:41:57 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `Users` CASCADE
;

DROP TABLE IF EXISTS `TimeRecords` CASCADE
;

DROP TABLE IF EXISTS `Tasks` CASCADE
;

DROP TABLE IF EXISTS `Rel_Files` CASCADE
;

DROP TABLE IF EXISTS `Projects` CASCADE
;

DROP TABLE IF EXISTS `Permissions` CASCADE
;

DROP TABLE IF EXISTS `Firms` CASCADE
;

DROP TABLE IF EXISTS `Files` CASCADE
;

DROP TABLE IF EXISTS `Comments` CASCADE
;

/* Create Tables */

CREATE TABLE `Users`
(
	`ID` CHAR(36) NOT NULL,
	`UserName` VARCHAR(50) NOT NULL,
	`Password` VARCHAR(50) NOT NULL,
	`FirstName` VARCHAR(50) 	 NULL,
	`LastName` VARCHAR(50) 	 NULL,
	`Permission_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_Users` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `TimeRecords`
(
	`ID` CHAR(36) NOT NULL,
	`Description` TEXT 	 NULL,
	`Date` DATE NOT NULL,
	`Start` TIME(0) NOT NULL,
	`End` TIME(0) 	 NULL,
	`User_ID` CHAR(36) NOT NULL,
	`Task_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_TimeRecords` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Tasks`
(
	`ID` CHAR(36) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`Description` TEXT 	 NULL,
	`StartDate` DATE NOT NULL,
	`PlanEndDate` DATE 	 NULL,
	`EndDate` DATE 	 NULL,
	`User_ID_Maintainer` CHAR(36) NOT NULL,
	`User_ID_Worker` CHAR(36) 	 NULL,
	`Project_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_Tasks` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Rel_Files`
(
	`ID` CHAR(36) NOT NULL,
	`File_ID` CHAR(36) NOT NULL,
	`Task_ID` CHAR(36) 	 NULL,
	`Project_ID` CHAR(36) 	 NULL,
	`User_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_Rel_Files` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Projects`
(
	`ID` CHAR(36) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`Code` VARCHAR(50) NOT NULL,
	`Description` TEXT 	 NULL,
	`StartDate` DATE NOT NULL,
	`PlanEndDate` DATE 	 NULL,
	`EndDate` DATE 	 NULL,
	`User_ID` CHAR(36) NOT NULL,
	`Firm_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_Projects` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Permissions`
(
	`ID` CHAR(36) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`IsAdmin` BOOL NOT NULL DEFAULT false,
	`CanManageUsers` BOOL NOT NULL DEFAULT false,
	`CanManageProjects` BOOL NOT NULL DEFAULT false,
	CONSTRAINT `PK_Permissions` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Firms`
(
	`ID` CHAR(36) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`Description` TEXT 	 NULL,
	`Email` VARCHAR(30) 	 NULL,
	`TelNumber` INTEGER 	 UNSIGNED NULL,
	CONSTRAINT `PK_Firms` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Files`
(
	`ID` CHAR(36) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`UploadDateTime` DATETIME(0) NOT NULL,
	`Data` BLOB NOT NULL,
	CONSTRAINT `PK_Files` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Comments`
(
	`ID` CHAR(36) NOT NULL,
	`Text` TEXT NOT NULL,
	`PostDateTime` DATETIME(0) NOT NULL,
	`User_ID` CHAR(36) NOT NULL,
	`Task_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_Comments` PRIMARY KEY (`ID`)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Users` 
 ADD CONSTRAINT `FK_Users_Permissions`
	FOREIGN KEY (`Permission_ID`) REFERENCES `Permissions` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `TimeRecords` 
 ADD CONSTRAINT `FK_TimeRecords_Tasks`
	FOREIGN KEY (`Task_ID`) REFERENCES `Tasks` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `TimeRecords` 
 ADD CONSTRAINT `FK_TimeRecords_Users`
	FOREIGN KEY (`User_ID`) REFERENCES `Users` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Tasks` 
 ADD CONSTRAINT `FK_Tasks_Projects`
	FOREIGN KEY (`Project_ID`) REFERENCES `Projects` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Tasks` 
 ADD CONSTRAINT `FK_Tasks_Users_Maintainer`
	FOREIGN KEY (`User_ID_Maintainer`) REFERENCES `Users` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Tasks` 
 ADD CONSTRAINT `FK_Tasks_Users_Worker`
	FOREIGN KEY (`User_ID_Worker`) REFERENCES `Users` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Rel_Files` 
 ADD CONSTRAINT `FK_Rel_Files_Files`
	FOREIGN KEY (`File_ID`) REFERENCES `Files` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Rel_Files` 
 ADD CONSTRAINT `FK_Rel_Files_Projects`
	FOREIGN KEY (`Project_ID`) REFERENCES `Projects` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Rel_Files` 
 ADD CONSTRAINT `FK_Rel_Files_Tasks`
	FOREIGN KEY (`Task_ID`) REFERENCES `Tasks` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Rel_Files` 
 ADD CONSTRAINT `FK_Rel_Files_Users`
	FOREIGN KEY (`User_ID`) REFERENCES `Users` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Projects` 
 ADD CONSTRAINT `FK_Projects_Firms`
	FOREIGN KEY (`Firm_ID`) REFERENCES `Firms` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Projects` 
 ADD CONSTRAINT `FK_Projects_Users`
	FOREIGN KEY (`User_ID`) REFERENCES `Users` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Comments` 
 ADD CONSTRAINT `FK_Comments_Tasks`
	FOREIGN KEY (`Task_ID`) REFERENCES `Tasks` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Comments` 
 ADD CONSTRAINT `FK_Comments_Users`
	FOREIGN KEY (`User_ID`) REFERENCES `Users` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 ;
